update license and readme to reflect authors' copyrights
freeCodeCamp/news-legacy pull request #25
Opened 2017-11-26 22:58 UTC by QuincyLarson

Closes #21

2017-11-27 05:25 UTC, raisedadead requested changes
```
* The articles in [`/src/pages`](/src/pages) and its subdirectories are a copyright of their original authors. If no author is stated, then it's copyright of freeCodeCamp.
```

2017-11-27 05:25 UTC, raisedadead commented
Just a minor edit to the text. Also, I don't have access to this repo so can some one merge it?

2017-12-01 20:23 UTC, QuincyLarson commented
@raisedadead I've granted you write access. Could you make the edit and merge this?

2017-12-02 03:55 UTC, raisedadead approved these changes

2017-12-02 04:03 UTC, merged